trigger:
  - '*'   # pipeline should be triggered on any changes to the repository (any branch)
pr:
  - '*'   # pipeline should also run on any pull requests

jobs:
- job: Build
  pool:
    name: Default

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
- job: DeployUAT
  displayName: 'Deploy to UAT'
  dependsOn: Build
  condition: eq(variables['Build.SourceBranchName'], 'main')
  pool:
    name: Default
  steps:
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to UAT web app'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(6c3e4386-799c-4546-96a2-1cb6c673dc85)'
      appType: 'webApp'
      WebAppName: 'DigitalSignature'
      deployToSlotOrASE: true
      ResourceGroupName: 'ClWebAPI_group'
      SlotName: 'uat'
      packageForLinux: '$(System.DefaultWorkingDirectory)/*/.zip'

- job: DeployProd
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: eq(variables['Build.SourceBranchName'], 'production')
  pool:
    name: Default
  steps:
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Production web app'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(6c3e4386-799c-4546-96a2-1cb6c673dc85)'
      appType: 'webApp'
      WebAppName: 'DigitalSignatureProd'
      deployToSlotOrASE: true
      ResourceGroupName: 'ClWebAPI_group'
      SlotName: 'production'
      packageForLinux: '$(System.DefaultWorkingDirectory)/*/.zip'