trigger:
  - '*'   # pipeline should be triggered on any changes to the repository (any branch)
pr:
  - '*'   # pipeline should also run on any pull requests

jobs:
- job: Build
  pool:
    name: Default

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'




- job: Deploy
  pool:
    name: Default

  steps:
  - checkout: self # checks out the source code from the repository
  - script: |
      if [ "$(Build.SourceBranchName)" == "main" ]; then
        echo "Deploying to UAT server..."
        # Add commands to deploy to UAT server
        az webapp deployment source config-zip --resource-group ClWebAPI_group --name DigitalSignature --src '$(System.DefaultWorkingDirectory)/**/*.zip'
      elif [ "$(Build.SourceBranchName)" == "production" ]; then
        echo "Deploying to Production server..."
        # Add commands to deploy to Production server
        az webapp deployment source config-zip --resource-group ClWebAPI_group --name DigitalSignatureProd --src '$(System.DefaultWorkingDirectory)/**/*.zip'
      else
        echo "No deployment for branch $(Build.SourceBranchName)"
      fi
